# Generated by Django 5.1.2 on 2024-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact_number', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=150)),
                ('Messages', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='python_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Project_description', models.TextField(max_length=1000)),
                ('Project_link', models.CharField(max_length=1000)),
                ('Project_created_on', models.DateField()),
                ('Project_technology', models.TextField(max_length=250)),
            ],
        ),
    ]
